In [10]:
import numpy as np
a=np.loadtxt('data.txt')
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [18]:
filedata=np.genfromtxt('data1.txt',delimiter=',')
filedata=filedata.astype('int32')
print(filedata)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [19]:
##Booelean MASKIND AND ADVANCED INDEXING
filedata>5


array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [False, False, False, False, False]])

In [21]:
filedata[filedata>5]

array([ 6,  7,  8,  9, 10])

In [25]:
#The above works on basis: We can index with a list in NumPy
a=np.array([1,2,3,4,5,6,7,8,9])
a[[1,5,8]]

array([2, 6, 9])

In [26]:
((filedata>5)&(filedata<11))

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [False, False, False, False, False]])

In [28]:
#~ stands for not
(~(filedata>5)&(filedata<11))

array([[ True,  True,  True,  True,  True],
       [False, False, False, False, False],
       [ True,  True,  True,  True,  True]])