In [1]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/AnacondaInstallation\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/AnacondaInstallation\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/AnacondaInstallation\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/AnacondaInstallation\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/AnacondaInstallation\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/AnacondaInstallation\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/AnacondaInstallation\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['D:/AnacondaInstallation\\Library\\include']
Supported SIMD extensions in this NumPy install:
    

In [4]:
#To check whether the array has zero or not
a=np.array([1,2,3,0])
print(np.all(a))

False


In [7]:
a1=np.array([0,0,0,0])
print(np.any(a1))

False


In [8]:
a2 = np.array([1, 0, np.nan, np.inf])
print(np.isfinite(a2))

[ True  True False False]


In [12]:
#nan- not a number, inf-infinity
a3 = np.array([1, 0, np.nan, np.inf])
print(np.isinf(a3))

[False False False  True]


In [13]:
a3 = np.array([1, 0, np.nan, np.inf])
print(np.isnan(a3))

[False False  True False]


In [31]:
import numpy as np
a4 = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
print(np.iscomplex(a4))
print(np.isreal(a4))
print(np.isscalar([3.2]))

[ True False False False False  True]
[False  True  True  True  True False]
False


In [42]:
x=np.array([4,6])
y=np.array([4,5])
print(np.greater(x,y))
print(np.less(x,y))
print(np.greater_equal(x,y))
print(np.less_equal(x,y))

[False  True]
[False False]
[ True  True]
[ True False]


In [6]:
import numpy as np


In [8]:
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])
print(np.equal(x,y))

[ True  True  True  True  True  True  True  True  True False]


In [9]:
print(np.allclose(x,y))  #Equal within a tolerance

True


In [13]:
x1=np.array([ 1, 7, 13, 105])
x1.itemsize
x1.nbytes

16

In [14]:
print("%d bytes" % (x1.size * x1.itemsize))


16 bytes


In [18]:
np.zeros(10)
np.ones(10)
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [22]:
np.arange(30,71)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [23]:
np.arange(30,71,2)

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

In [26]:
#Random Number between 0 and 1
np.random.normal(0,1)

0.1645471180407954

In [31]:
np.random.sample(20)

array([0.39099615, 0.22530709, 0.02463614, 0.50975275, 0.06073114,
       0.74962989, 0.24632309, 0.61549586, 0.92812174, 0.80931921,
       0.60078616, 0.15020124, 0.99263591, 0.47511128, 0.04891864,
       0.59111241, 0.32264743, 0.64846174, 0.56423913, 0.28781398])

In [29]:
#Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.
np.random.normal(0,1,15)

array([ 1.45182928, -0.06494388, -2.23922222,  0.94936745, -1.13234192,
        1.91139083,  0.48759773,  1.19046232,  1.07451662,  0.51366432,
        0.0328469 , -1.10386073, -0.14624978,  0.33483607,  0.12488145])

In [42]:
#Create a vector with values ​​ranging from 15 to 55 and print all values ​​except the first and last
a=np.arange(15,55)
print(a)
print(a[1:-1])

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


In [50]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[1,2,3]])

In [51]:
for x in np.nditer(a):
    print(x,end=" ")

1 2 3 4 5 6 7 8 9 1 2 3 

In [65]:
#Write a NumPy program to create a vector of length 10 with values ​​evenly distributed between 5 and 50.
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [68]:
x=np.arange(0,21)
x[(x>=9)&(x<=15)]*=-1
print(x)

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [76]:
x=np.ones([10,10])
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [83]:
x=np.zeros([5,5])
x[0,0]=1
x[1,1]=2
x[2,2]=3
x[3,3]=4
x[4,4]=5
x


array([[1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 5.]])

In [84]:
np.diag([1, 2, 3, 4, 5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [89]:
a=np.array([[1,2],[3,4]])
np.sum(a)
np.sum(a,axis=0)
np.sum(a,axis=1)

array([3, 7])

In [91]:
import numpy as np
import os
x = np.arange(12).reshape(4, 3)
print("Original array:")
print(x)
header = 'col1 col2 col3'
np.savetxt('temp.txt', x, fmt="%d", header=header) 



Original array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [92]:
#list to array
x=[1,2,3,4,5]
np.array(x)

array([1, 2, 3, 4, 5])

In [95]:
x=np.arange(2,11).reshape(3,3)
x

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [99]:
a=np.arange(12,38)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

In [101]:
b=a[::-1]
b

array([37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 19, 18, 17, 16, 15, 14, 13, 12])

In [109]:
a=[1,2,3,4]
b=np.asfarray(a)
b

array([1., 2., 3., 4.])

In [113]:
x=np.sqrt([1+0j])
y=np.sqrt([2+0j])
print(x.real)
print(y.real)

[1.]
[1.41421356]


In [115]:
x=np.array([1,2,3,4])
x.size #size of an arrray



4

In [116]:
x.itemsize #Length of one array in bytes

4

In [117]:
x.nbytes  #Total bytes consumed by the elements of the array

16

In [119]:
a=np.array([1,2,3,4])
b=np.array([1,2])
np.in1d(a,b)  #compare a and b

array([ True,  True, False, False])

In [123]:
a=np.array([[1,2],[3,4]])
b=np.array([[1,2],[6,4]])
np.in1d(a,b)

array([ True,  True, False,  True])

In [124]:
a=np.array([1,2,3,4])
b=np.array([1,2,5,6])
np.intersect1d(a,b)

array([1, 2])

In [125]:
a=np.array([1,1,2,2,3,4,5])
np.unique(a)

array([1, 2, 3, 4, 5])

In [128]:
a=np.array([1,2,3,4])
b=np.array([1,2,5,6,7])
np.setdiff1d(a,b)

array([3, 4])