In [3]:
import numpy as np


In [40]:
a=np.array([2,3,4], dtype='int16')
print(a)

[2 3 4]


In [41]:
b=np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [42]:
#Get dimension
a.ndim


1

In [43]:
b.ndim

2

In [44]:
#Get shape
a.shape


(3,)

In [45]:
#get type
a.dtype

dtype('int16')

In [46]:
a.itemsize

2

In [47]:
a.nbytes

6

In [48]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [49]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [50]:
#Get a specific element from an array[r,c]
a[1,5]

13

In [51]:
#Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [52]:
#Get a specific column
a[:,2]

array([ 3, 10])

In [53]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0,1:6:2]
a[0,1:-1:2]

array([2, 4, 6])

In [54]:
a[1,5]=20

In [55]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [62]:
a[:, 2]= [1,2]


In [63]:
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [64]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [65]:
b[0,1,1]

4

In [67]:
#replace
b[:,1,:]=[[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [70]:
#ALl zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [75]:
np.ones((2,3),dtype='int32')

array([[1, 1, 1],
       [1, 1, 1]])

In [76]:
#Any other num
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [77]:
#Anyother num to replace the total array
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [78]:
#Random decimal number
np.random.rand(2,3)

array([[0.61410157, 0.23784248, 0.60558779],
       [0.54889301, 0.08347492, 0.51779002]])

In [82]:
#this will give random values to the shape sihape of a
np.random.random_sample(a.shape)

array([[0.04480635, 0.85498827, 0.44924998, 0.54565741, 0.77087471,
        0.48212345, 0.44778099],
       [0.97235999, 0.04787862, 0.42505615, 0.59771962, 0.20557737,
        0.35954499, 0.23784425]])

In [83]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 4,  5,  5],
       [-4, -4, -3],
       [-4, -3,  1]])

In [84]:
#Identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [86]:
#repeat and array
arr=np.array([1,2,3])
r1=np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [88]:
#for 2-d-Repeat an array
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [97]:
#Handpon
output=np.ones((5,5))
print(output)
zeros=np.zeros((3,3))
print(zeros)
zeros[1,1]=9
output[1:4,1:4]=zeros
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [100]:
a=np.array([1,2,3])
b=a.copy()
print(b)

[1 2 3]


In [111]:
a=np.array([1,2,3])
a+2

array([3, 4, 5])

In [112]:
a-2

array([-1,  0,  1])

In [113]:
a*2

array([2, 4, 6])

In [114]:
a=np.array([1,2,3])
b=np.array([4,5,6])
a+b

array([5, 7, 9])

In [115]:
a**2

array([1, 4, 9], dtype=int32)

In [117]:
np.sin(a)
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [8]:
##Linear Alegra
a= np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [10]:
#Determinant
c=np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

In [17]:
c1=np.array([[20,30,3],[3,6,2],[4,7,2]])
print(c1)
np.linalg.det(c1)

[[20 30  3]
 [ 3  6  2]
 [ 4  7  2]]


10.999999999999991

In [19]:
#Transpose
a=np.array([[1,1,1],[2,2,2],[3,3,3]])
print(a)
at = a.transpose()
print(at)

[[1 1 1]
 [2 2 2]
 [3 3 3]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [27]:
#Eigen value
e=np.array([[1,1],[2,2]])
print(e)
e1,e2=np.linalg.eig(e)
print(e1)
print(e2)
#e1-Eigen value, e2-eigen Vector

[[1 1]
 [2 2]]
[0. 3.]
[[-0.70710678 -0.4472136 ]
 [ 0.70710678 -0.89442719]]


#Statistics

In [28]:
stats=np.array([[1,2,3],[4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [29]:
np.min(stats)

1

In [35]:
np.min(stats,axis=0)

array([1, 2, 3])

In [36]:
np.max(stats)

6

In [37]:
np.sum(stats)

21

In [39]:
#Reorganizing array
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after=before.reshape(4,2)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [41]:
#Vertically stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [42]:
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [43]:
#Horizontal stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [78]:
#Miscellaneous
#Load Data from file
filedata=np.genfromtxt('data.txt',delimiter=',')
print(filedata)

[nan nan nan]


In [54]:
import numpy as np
y=np.loadtxt("data.txt")

ValueError: could not convert string to float: '1,2,3,4,5,6,7,'

In [53]:
f=open("data.txt",'r')
print(f.read())

1,2,3,4,5,6,7,
8,9,10,11,12,13,
14,15,16,17,18,19


In [60]:
f=open("data.txt",'r')
print(f.readline())
print(f.readline())

1,2,3,4,5,6,7,

8,9,10,11,12,13,



In [62]:
#to avoid the space in between lines
f=open("data.txt",'r')
print(f.readline(),end="")
print(f.readline())

1,2,3,4,5,6,7,
8,9,10,11,12,13,



In [65]:
w=open("Write",'w')
w.write("Hello World")

11

In [68]:
w=open("Write",'a')
w.write("Welcome")

7

In [70]:
#Copying data from one file to other
for data in f:
    w.write(data)
    

In [74]:
i=open("Photo.JPG",'rb')


In [76]:
i1=open("Myphoto.JPG",'wb')
for n in i:
    i1.write(n)

In [77]:
#Advance Indexing in Numpy
